### PR TITLE
Fix default DocumentDbStorageOptions

### PR DESCRIPTION
**Pull request by savbace**
- align default `DocumentDbStorageOptions` with documentation comments
- fix spelling in `DocumentDbStorage.ToString()`

### CODE REVIEW

**Comment by savbace** [comment]
`Hangfire.Azure.DocumentDbDistributedLockException` #24 seems to not appear anymore after making `QueuePollInterval` less frequent (2 **minutes** instead of 2 **seconds**).

**Comment by imranmomin** [comment]
@savbace nice you were able to fine tune your settings. You can still change the settings without the PR.

**Comment by savbace** [comment]
@imranmomin yes, I was able to change settings without the PR. But the main goal of PR was to eliminate inconsistency between XML documentation and code in `DocumentDbStorageOptions`. For example check what docs say about `DocumentDbStorageOptions.QueuePollInterval` default value and what an actual default value set in constructor is.

**Comment by imranmomin** [comment]
the document shows how you can override the options. It was not intended to be same as defaults. If it has led to a confusion I'm sorry. I will put sometime on the documentation to mention the defaults

**Comment by savbace** [comment]
it would be great! thanks!

**Pull request closed without merging**
